

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The Azerbaijani Forces started engineering work and fortifying their positions on the surrendered and strategic mount sartsasar and several other strategic heights in Nagorny Karabakh. 1 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijani Defense Ministry reports on taking control of Mount Buzdukh and nearby heights in Karabakh. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijani Ministry of Defense: Our armed forces have taken control of some heights in the Nagorno-Karabakh region. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">3rd Azerbaijani strike: the drone hit an howitzer towed to an Ural truck. However, the truck later exploded, damaging and destroying other vehicles and and equipment. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The Republic of Azerbaijan has repeatedly stated that, contrary to the tripartite statement, the presence of Armenian armed forces and illegal Armenian armed groups in the territories of Azerbaijan, where peacekeepers of the Russian Federation are temporarily stationed, remains a source of danger. The demilitarization of those territories, the complete withdrawal of Armenian troops from there and the disarmament of illegal Armenian armed elements are absolutely necessary - Ministry of Defense. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Kirkhgiz, Sarıbaba and a number of other important ruling heights have been taken under control - Azerbaijan. Azerbaijan Ministry of Defense: The elements of illegal Armenian armed groups tried to seize the Kirkhgiz hill located in the mountain range covering the territory of Kalbajar and Lachin regions and to establish new combat positions there. The Ministry of Defense informed APA about this. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijani side reports they have killed 4 Armenian soldiers and wounded 15. They call it "an anti-terrorist operation against illegal Armenian armed groups in the territory of Azerbaijan, where the Russian peacekeeping contingent is temporarily stationed". 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Exclamation Renewed fighting in Karabakh as Azerbaijani forces reportedly attempt to advance near Lachin corridor, regions only link to Armenia. Karabakh Armenian side reports 7 injured. Azerbaijani side using mortars and UAVs. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijan Ministry of Defense: The information published in the Armenian press is false. The information published in the Armenian press about the Azerbaijani Army units firing in the direction of illegal Armenian armed groups in the territory of Azerbaijan, where Russian peacekeepers are temporarily stationed, is false, provocative and misleading.. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijan will supply the EU with up to 20 billion cubic meters of gas per year — Ursula von der Leyen signed a strategic partnership memorandum with the President of Azerbaijan Ilham Aliyev in Baku. 1 month ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Tbilisi City Court on Thursday denied bail for the host of the Mtavari Arkhi TV channel, Lasha Nakaidze, who was arrested on Tuesday on charges of rape, domestic violence and threats and faces six to eight years in prison if found guilty. 2 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Polish OSCE Chairmanship: We are extremely concerned about reported armed incidents and casualties in the South Caucasus. We urge Armenia and Azerbaijan to take all necessary measures to bring de-escalation and resume dialogue. We remain committed to support all efforts aimed at consolidating peace in the region. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">PM @GharibashviliGe, President @Zourabichvili_S, Tbilisi Mayor @kakhakala and Govt ministers paid tributes to the 8 victims in the rescue helicopter crash in Gudauri. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The Mi-8 helicopter belonging to the Georgian Border Police crashed while carrying out the mission of rescuing paragliders in Gudauri. 3 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Putin at meeting with Tokayev: Defense Ministries of Russia and Kazakhstan are preparing joint exercises within the framework of the CSTO. 1 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Russian defense minister held talks with the Minister of Defense of Armenia, the situation in Nagorno-Karabakh was discussed. 4 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The meeting between President Erdogan and Putin ended. The meeting lasted more than four hours.. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Russia accuses Azerbaijan of violating ceasefire in Nagorno-Karabakh. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">16 bodies found at the market that was destroyed in fire in Yerevan. 4 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The Armenian Ministry of Emergency Situations reports that as a result of an explosion and a fire in a shopping center in Yerevan, one person died, 20 were injured. 6 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Fire at Surmalu market in Yerevan. 6 day ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Nagorny Karabakh army: 2 soldiers wounded. 1 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">3 soldiers were killed and 14 wounded in the fighting between Azerbaijani and Armenian forces in the Nagorno-Karabakh region. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">The Ministry of Foreign Affairs of Armenia accused Azerbaijan of violating the tripartite statement of November 9: "We consider unacceptable the statements of the Azerbaijani side, which make an attempt to unilaterally change the legal regime of the Lachin corridor, established by paragraph 6 of the tripartite document, and confirm that the route passing through the Lachin corridor, can only be changed according to a plan approved by the parties who signed the document". 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Today, Head of Nagorny Karabakh authorities, Arayik Harutyunyan signed a decree, according to which a partial military mobilization was declared in the territory from August 3, 2022. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Armenia files third interstate complaint against Azerbaijan to the European Court of Human Rights (ECHR). The complaint refers to the violation of the rights of the civilians as a result of the aggression undertaken by Azerbaijan against the villages of Khramort & Parukh in Nagorny Karabakh. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">One Armenian serviceman wounded as result of clashes with Azerbaijani troops in Nagorno-Karabakh. 2 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Armenias Ministry of Defence also reported ceasefire violations by Azerbaijan on the countrys eastern border. No casualties from the Armenian side reported. 3 week ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://caucasus.liveuamap.com" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Units of Armed Forces of Armenia deployed in Karabakh to return to Armenia - secretary of Security Council of Armenia. 1 month ago - Liveuamap</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Senior Armenian, Azerbaijani Officials Meet In Brussels. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Armenia Mourns Victims Of Yerevan Market Explosion As Search For Survivors Continues. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Yerevan Market Director Denies Safety Breach As Blasts Death Toll Rises To 16. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">At Least Seven Dead, 22 Still Missing As Rescuers Fight Yerevan Market Fire. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">One Dead After Fireworks Blast Starts Fire At Armenian Market. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Armenian Readies Delayed Census For October. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Azerbaijani Official Fired, Charged Over Leaked Sex Video. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Leaving Aghavno, Returning To Zabux: Hopes And Fears As Armenia Hands Over Village To Azerbaijan. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Interview: With The 2008 Georgia War, We Knew What Was Coming, But We Were Slow To Believe It. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">I Plant Things And They Grow: In Georgia, A 76-Year-Old Woman Becomes An Art Sensation. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">New Despair For Ukrainian Refugees As Georgia Ends Program Housing Them In Hotels. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Russian Extremists Target A Bar In Tbilisi Where Patrons Have To Denounce Putin. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Annexation: Georgia Balks At Handover Of Abkhaz Land To Russia. - Radio Free</a></ul></li></div>';

document.getElementById('div2').innerHTML += '<div><ul><li style="list-style-type: square;"><a href="https://www.rferl.org/p/5498.html" style="padding-top: 3%; text-decoration: none; font-size: larger; font-weight: lighter;">Amid Tight EU Scrutiny, Georgian Dream Feuds With Western Envoys. - Radio Free</a></ul></li></div>';